In [1]:
!git clone https://github.com/soerenab/AudioMNIST.git

Cloning into 'AudioMNIST'...
remote: Enumerating objects: 30137, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 30137 (delta 9), reused 4 (delta 1), pack-reused 30119 (from 1)
Receiving objects: 100% (30137/30137), 944.54 MiB | 21.93 MiB/s, done.
Resolving deltas: 100% (35/35), done.
Updating files: 100% (30018/30018), done.

In [2]:
!ls

AudioMNIST  sample_data

In [3]:
!ls AudioMNIST/data

01  05	09  13	17  21	25  29	33  37	41  45	49  53	57  audioMNIST_meta.txt
02  06	10  14	18  22	26  30	34  38	42  46	50  54	58
03  07	11  15	19  23	27  31	35  39	43  47	51  55	59
04  08	12  16	20  24	28  32	36  40	44  48	52  56	60

In [5]:
import json

meta_path = "AudioMNIST/data/audioMNIST_meta.txt"

with open(meta_path, "r") as f:
    metadata = json.load(f)

print(type(metadata))

<class 'dict'>

In [6]:
metadata["01"]

{'accent': 'german',
 'age': 30,
 'gender': 'male',
 'native speaker': 'no',
 'origin': 'Europe, Germany, Wuerzburg',
 'recordingdate': '17-06-22-11-04-28',
 'recordingroom': 'Kino'}

In [7]:
sample_file = "5_01_12.wav"

parts = sample_file.replace(".wav","").split("_")

digit = parts[0]
speaker = parts[1]

print("Digit:", digit)
print("Speaker:", speaker)

Digit: 5
Speaker: 01

In [8]:
gender = metadata[speaker]["gender"]

print("Gender:", gender)

Gender: male

In [9]:
import os
import glob

file_paths = []
digits = []
genders = []

# go through all wav files
audio_files = glob.glob("AudioMNIST/data/*/*.wav")

for file in audio_files:

    filename = os.path.basename(file)

    # split filename
    parts = filename.replace(".wav","").split("_")

    digit = parts[0]
    speaker = parts[1]

    # get gender from metadata
    gender = metadata[speaker]["gender"]

    # store results
    file_paths.append(file)
    digits.append(digit)
    genders.append(gender)

In [10]:
print("Total files:", len(file_paths))
print("Example:")
print(file_paths[0], digits[0], genders[0])

Total files: 30000
Example:
AudioMNIST/data/21/0_21_40.wav 0 male

In [12]:
import pandas as pd

df = pd.DataFrame({
    "file": file_paths,
    "digit": digits,
    "gender": genders
})

df.head()

                             file digit gender
0  AudioMNIST/data/21/0_21_40.wav     0   male
1   AudioMNIST/data/21/3_21_1.wav     3   male
2  AudioMNIST/data/21/3_21_20.wav     3   male
3  AudioMNIST/data/21/2_21_31.wav     2   male
4   AudioMNIST/data/21/1_21_3.wav     1   male

In [13]:
df["gender"].value_counts()

gender
male      24000
female     6000
Name: count, dtype: int64

In [14]:
df["digit"].value_counts().sort_index()

digit
0    3000
1    3000
2    3000
3    3000
4    3000
5    3000
6    3000
7    3000
8    3000
9    3000
Name: count, dtype: int64

In [15]:
sample_audio = file_paths[0]

print(sample_audio)

AudioMNIST/data/21/0_21_40.wav

In [16]:
import librosa
import numpy as np

audio, sr = librosa.load(sample_audio, sr=None)

mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=13)

print("MFCC shape:", mfcc.shape)

MFCC shape: (13, 71)